pipeline {
   tools {
     maven "M3"
   }
   agent any
   stages {
     stage("Preparation") { 
       steps {
         git 'https://github.com/jglick/simple-maven-project-with-tests.git'
       }
     }
     stage("Build") {
       steps {
         sh "mvn -Dmaven.test.failure.ignore clean package"
       }
     }
   } 
   post {
      always {
	    junit "**/target/surefire-reports/TEST-*.xml"
      }
      success {
        archive "target/*.jar"
      }
   }
}